Repository shielddx/oatmeal-protocol, pull requests merged in 2019-05, with the labels that each got.

#2 Add typehint to MAX_HEARTBEAT_GAP_SEC
  python/oatmeal/device.py
Labels: needs-rubberstamp

#3 Fix MAX_HEARTBEAT_GAP_SEC member mis-named
  python/oatmeal/protocol.py
Labels: needs-rubberstamp

#1 Add CircleCI setup readme
  .circleci/README.md
Labels: needs-rubberstamp

#5 Fix filename in library.properties includes field
  library.properties
Labels: needs-merge

#4 PyPi upload script
  CONTRIBUTING.md
  python/setup.py
Labels: needs-rubberstamp

#8 Remove symlinks; Keep Arduino lib spec v1.5; Tell Makefile our lib is called 'src'
  CONTRIBUTING.md
  docs/Doxyfile
  examples/ArduinoIDEExample/Makefile
  examples/ArduinoIDEExample/oatmeal_protocol
  examples/SimpleMemoryGetSet/Makefile
  examples/SimpleMemoryGetSet/oatmeal_protocol
  examples/SmallHardwareExample/Makefile
  examples/SmallHardwareExample/oatmeal_protocol
  library.properties
Labels: needs-review
